spring.application.name=auth

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/authdb

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID

spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET

# JWT Secret Key
jwt.secret=your-super-secret-key-which-should-be-very-long-for-production

jwt.expiration=86400000